### ISSUE TITLE
Configuration file outline

### ISSUE THREAD

**Issue by tgross35** [pluots/zspell#8]
We will keep everything in ~/.zspell. Users can place dictionaries there. Directory contents

```
config.toml
registry.toml
dictionaries/
  personal.txt
  dic1.dic
  dic1.aff
  dic1.license
  dic1.readme / dic.readme.md
```

config.toml
```toml

# If empty, use the system's language
default_language = ""
extra_search_paths = [
  ""
]
include_default_search_paths = true


```

registry.toml
```toml
# This file is automatically generated
[[dictionary]]
name = "en_US"
version = ""
license = "dictionaries/en_US.license"
dict_file = "dictionaries/en_US.dic"
affix_file = "dictionaries/en_US.aff"
released= 1979-05-27T07:32:00Z
acquired = 1979-05-27T07:32:00Z
source = "github.com/..."

```
